name: Backup

on:
  workflow_dispatch:    
  schedule:
    - cron:  '05 17 * * *'

jobs:
  gitrepos-backupto-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'amitsaha/gitbackup'
      - name: Setup
        run: |
          go build
 
      - name: Get GitHub User Data
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          ./gitbackup -service github -use-https-clone -ignore-fork -ignore-private -github.repoType owner -github.namespaceWhitelist "saltbo,bonaysoft" -bare

      - name: Push to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: 'ap-southeast-2'
        run: |
          sudo gem install gitkeep
          gitkeep ~/.gitbackup/github.com/
          aws --endpoint-url https://cos.ap-beijing.myqcloud.com s3 sync ~/.gitbackup/github.com/. s3://saltbo-1255970412/pvc-9e2337bc-df3e-43f9-a6b7-8a9b3b4ad079_default_git
